# Generated by Django 5.0.7 on 2024-07-19 16:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EventType',
            fields=[
                ('id', models.CharField(max_length=3, primary_key=True, serialize=False)),
                ('event_type', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('pokemon_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('birth_year', models.IntegerField()),
                ('division', models.CharField(max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='ChampionshipPoints',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('highest_place', models.IntegerField()),
                ('lowest_place', models.IntegerField()),
                ('points', models.IntegerField()),
                ('kicker', models.IntegerField()),
                ('event_type', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='tournaments.eventtype')),
            ],
        ),
        migrations.CreateModel(
            name='Tournament',
            fields=[
                ('id', models.CharField(max_length=13, primary_key=True, serialize=False)),
                ('event_name', models.CharField(max_length=100)),
                ('event_date', models.DateField()),
                ('event_type', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='tournaments.eventtype')),
            ],
        ),
        migrations.CreateModel(
            name='Standings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('division', models.CharField(max_length=3)),
                ('placement', models.IntegerField()),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='tournaments.player')),
                ('tournament_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='tournaments.tournament')),
            ],
        ),
        migrations.CreateModel(
            name='TournamentDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('round', models.IntegerField()),
                ('table_number', models.CharField(max_length=4)),
                ('result', models.CharField(max_length=1)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='tournaments.player')),
                ('tournament_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='tournaments.tournament')),
            ],
        ),
    ]
