# Generated by Django 5.0.7 on 2024-07-19 17:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ChampionshipPoints',
            new_name='ChampionshipPoint',
        ),
        migrations.RenameModel(
            old_name='Standings',
            new_name='Standing',
        ),
        migrations.RenameModel(
            old_name='TournamentDetails',
            new_name='TournamentDetail',
        ),
    ]
