# Generated by Django 5.0.7 on 2024-07-19 23:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0002_rename_championshippoints_championshippoint_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tournamentdetail',
            old_name='tournament_id',
            new_name='tournament',
        ),
    ]
