# Generated by Django 5.0.7 on 2024-07-20 02:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0003_rename_tournament_id_tournamentdetail_tournament'),
    ]

    operations = [
        migrations.RenameField(
            model_name='standing',
            old_name='tournament_id',
            new_name='tournament',
        ),
    ]
