# Generated by Django 5.2.2 on 2025-06-09 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0005_filerun'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournamentdetail',
            name='table_number',
            field=models.IntegerField(),
        ),
    ]
