# Generated by Django 5.2.4 on 2026-01-05 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0006_alter_tournamentdetail_table_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='Division',
            fields=[
                ('name', models.CharField(max_length=3, primary_key=True, serialize=False)),
                ('sort_order', models.IntegerField()),
            ],
        ),
    ]
