# Generated by Django 5.2.4 on 2026-01-05 14:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0007_division'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='division',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='tournaments.division'),
        ),
    ]
